### ISSUE TITLE
Idea to encrypt

### ISSUE THREAD

**Issue by pavlukivan** [MarcuzD/TerraInveditDroid#17]
Take old .player file, then copy it to Terraria, and launch it, (To create encrypted file) then bruteforce key and look if it's similar (not the same) to the old one. Or I can try it myself...

**Comment by pavlukivan** [comment]
I already created a version, that works with newest Terraria. I updated items list and moved old .player file into the program. The program copies that file into Terraria data and edits it, then Terraria converts it to new format. I abandoned it, but it may be temporary workaround.

**Comment by MarcuzD** [comment]
Well, the problem is the way Blowfish works. Sadly, it encrypts in series of 8 bytes, so if I were to make a decryption table, it would take exactly 295147905179352825856 bytes (268435456 Terrabytes) to store that file that holds the decryption values for every save file, so I'll have to really find those keys :sad:

**Comment by pavlukivan** [comment]
maybe you should try workaround that I described...

**Comment by MarcuzD** [comment]
Well, you can't fabricate a pplayer file from scratch, because it contains unique identifiers, so it would be a bad idea

**Comment by VisualStudio-zz** [comment]
I posted the keys here:
http://www.se7ensins.com/forums/threads/terraria-mobile-savegame-mods.1526318/

It could have an IV and maybe openpgp mode because the final block isn't 8 bytes. If it does have an IV then it needs to be 8 bytes, I've been messing around with it for a while and I'll report back if I get anything done.

**Comment by MarcuzD** [comment]
Oooh, it looks promising! I'll take a look ASAP!

**Comment by VisualStudio-zz** [comment]
This is a script I threw together for it so you can get a better understanding.
https://pastebin.com/eXM6qWVm

**Comment by MarcuzD** [comment]
Hmm... how should I credit you? This is awesome! I'll port it to Java in a bit, then I'll push an update :smile:

**Comment by MarcuzD** [comment]
I have read thru' the thread again, and the code, but I don't seem to be able to decrypt the player file properly with that key (I have tried treating the key as an ASCII key, I tried parsing it as a hexadecimal-encoded key, but I still don't have luck decrypting the savedata).

Btw, the save file is correctly padded. There's a LE16 (little-endian 16bit number) on the start of the file that contains the save file version, and that's unencrypted. Everything after the save file version is encrypted.

**Comment by VisualStudio-zz** [comment]
I updated it to that spec.

**Comment by MarcuzD** [comment]
I have made little progress with getting the keys: I'll try to reconstruct the decryption code in C, then I'll port the C code to Java :stuck_out_tongue:

**Comment by MarcuzD** [comment]
After this long time, I finally managed to RE the Blowfish code from Terraria, and I managed to decrypt my player file \o/ ([proof](https://puu.sh/smxo3/c675a9248f.png))
Now all I need to do is to port the C++ code to Java :neutral_face:

**Comment by pavlukivan** [comment]
That's great!

**Comment by VisualStudio-zz** [comment]
Drop me that code and I'll do it to python too.

**Comment by MarcuzD** [comment]
Oh wait, I forgot to RE the encryption :joy: At least the decryption part is done :stuck_out_tongue:

**Comment by VisualStudio-zz** [comment]
I can reverse it easily, pastebin it or something.

**Comment by MarcuzD** [comment]
Damn, I don't know what's happening, but it's impossible to get the C++ code to work in Java :/ I'll upload the C++ code in a few hours, so someone could attempt to port it to Java, because after all these hours it's just not working... I blame Java's BigEndianness :< I'm used to LittleEndian, not BigEndian :<

**Comment by VisualStudio-zz** [comment]
Yeah, I feel like I can get it working.

**Comment by pavlukivan** [comment]
If you'll not succeed in porting c++ code to java, you can use NDK

**Comment by MarcuzD** [comment]
> NDK
oh, please no ._. I'll upload the C++ code in a bit instead! I have war flashbacks from using the NDK...

**Comment by MarcuzD** [comment]
I posted the sooscode to [Github Gist](https://gist.github.com/MarcuzD/52679f4db658bd7928627abd860b254a) :stuck_out_tongue:

**Comment by VisualStudio-zz** [comment]
They're the keys I posted way earlier on aren't they?

**Comment by MarcuzD** [comment]
Ye, except that you mixed up the keys :stuck_out_tongue_winking_eye: Other than the accidental derp, those are the real encryption keys :stuck_out_tongue:

**Comment by VisualStudio-zz** [comment]
That things you labeled as "garbage" are s-boxes btw.

**Comment by MarcuzD** [comment]
I know (as you may see from the [comments](https://gist.github.com/MarcuzD/c3ebd27215357a2009adbc3bebb1f1ae#file-bf-cpp-L50)), but I generated those numbers from the original binary with a script, but I was just too lazy to re-categorize them :stuck_out_tongue:

**Comment by VisualStudio-zz** [comment]
From what it looks like they're using custom Encipher and Decipher functions.

**Comment by MarcuzD** [comment]
Btw, I ***finally*** managed to decrypt my player file in Java (it turns out Java's endianness was confusing me), so the update is only a few mins/hours away :stuck_out_tongue:

**Comment by pavlukivan** [comment]
Awesome! Finally it's almost done



On Sat, Nov 19, 2016 at 9:19 PM +0700, "MarcusD" <notifications@github.com<mailto:notifications@github.com>> wrote:


Btw, I finally managed to decrypt my player file in Java (it turns out Java's endianness was confusing me), so the update is only a few mins/hours away ?

-

**Comment by MarcuzD** [comment]
Yay, issue can be closed \o/

https://puu.sh/snsCT/18002eadd8.png
