### ISSUE TITLE
No way to manually enter ID of item

### ISSUE THREAD

**Issue by Avamander** [MarcuzD/TerraInveditDroid#5]
Please allow manual entering of a item ID. Also, sort the item list by ID and allow entering item names that contain spaces in them.

**Comment by MarcuzD** [comment]
You can manually enter item ID by double- or triple-tapping on the field you want to enter. This is standard Android functionality. This works on my both devices running 4.0.1 and 4.4.2

Also, the items are sorted by item ID, so it'll be a bit easier to find relevant items.

**Comment by Avamander** [comment]
The sorting is definitely not right at least not on my phone.

**Comment by MarcuzD** [comment]
Could you please post me a screenshot?

**Comment by Avamander** [comment]
![Example](https://i.imgur.com/I4c0ifs.png)

**Comment by Avamander** [comment]
I am also unable to enter the ID, should I double tap the item field, right? My device is running Android 4.4.4 so I don't know what's the issue :/

**Comment by MarcuzD** [comment]
Wow, that's just weird.

**Comment by Avamander** [comment]
Should I create another issue for that one? Because I'm still unable to only enter the ID.

**Comment by MarcuzD** [comment]
Added an ItemID selector number scrollbar, it'll be out in the next release :wink:
