### ISSUE TITLE
Automatic detection of encrypted .player files

### ISSUE THREAD

**Issue by Avamander** [MarcuzD/TerraInveditDroid#7]
It would be nice if the app autodetected encrypted files and would disable editing and saving.

**Comment by MarcuzD** [comment]
As now that I know the save file structure a bit more than when I wrote this, I should be able to 99% detect if the savefile is corrupted. I'll look into it.

**Comment by MarcuzD** [comment]
Added save file version detection, now it detects if the savefile is encrypted, and removed the padding adjuster, it'll now calculate the offset instead of guessing it, it should be out in the next release
