### ISSUE TITLE
Padding error,items showing up on player data file but not in game

### ISSUE THREAD

**Issue by Jasper1224** [MarcuzD/TerraInveditDroid#8]
Well,it says my player file is corrupted,wants to mod the padding but i set it to auto,yes,and just repeats itself continuously. Stopped the loop by pressing no. App shows weird objects like mahogany pianos,which i can't hace,as i just started this world,missing items,apparently,and just plain doesn't work. Am using 5.0 android,but not samsung,saw that there was a problem with it.

**Comment by MarcuzD** [comment]
I suspect that you're using the newest Terraria, right? Since 1.2.11211, the save is encrypted with Blowfish. Have you read  through the readme?

**Comment by Jasper1224** [comment]
I did,just didn't realise that last one was encrypted...sorry

**Comment by MarcuzD** [comment]
Added encrypted file detection, and removed the padding stuff, it'll be out in the next release

**Comment by Jasper1224** [comment]
Ah,so the great master has solved the encryption problem? Good job,the
citizens of hacking terraria mobile thank you for your hard work.

**Comment by MarcuzD** [comment]
No, sadly I didn't yet found the encryption key, but at least the program now won't load the player file if it's encrypted, and it'll warn you about it. Sorry :(

**Comment by Jasper1224** [comment]
Oh well,at least you're trying!
